spring.application.name=emstest
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/testeng?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.username=manjunathkesarur09@gmail.com
spring.mail.password=ndht sajh pjtj pbwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true